name: 'fraud_pipeline'
version: '1.0.0'
config-version: 2

profile: 'fraud_pipeline'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  fraud_pipeline:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
